version: "3.7"
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    image: ethsign-api
    volumes:
      - .:/ethsign-api
      - static_volume:/ethsigns-app/app/static/
    entrypoint: ["/bin/bash", "-c", "/ethsigns-app/docker/start_app.sh"]
    stdin_open: true
    tty: true
    environment:
      - FLASK_APP=${FLASK_APP}
      - DATABASE_URI=${DATABASE_URI}
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - SQLALCHEMY_TRACK_MODIFICATIONS=${SQLALCHEMY_TRACK_MODIFICATIONS}
  proxy:
    image: ethsign-api-nginx
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/:/etc/letsencrypt/
      - static_volume:/ethsigns-api/static/
    restart: always
volumes:
  static_volume: