version: "3.7"
services:
  database:
    restart: always
    image: postgres:13.2
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - database_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5433"

  redis:
    image: redis
    ports:
      - "6378:6379"
    expose:
      - "6378"
    volumes:
      - redis_volume:/data
  app:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    image: ethsign-api
    volumes:
      - .:/ethsign-api
      - static_volume:/ethsigns-app/app/static/
    entrypoint: ["/bin/bash", "-c", "/ethsigns-app/docker/start_app.sh"]
    depends_on:
      - redis
      - database
    stdin_open: true
    tty: true
    environment:
      - FLASK_APP=${FLASK_APP}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - SQLALCHEMY_TRACK_MODIFICATIONS=${SQLALCHEMY_TRACK_MODIFICATIONS}

      - CELERY_BROKER_URL=redis://redis
      - CELERY_RESULT_BACKEND=redis://redis
      - REDIS_URL=redis://redis
      - RPC_URL=${RPC_URL}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - IPFS_GATEWAY_URL=${IPFS_GATEWAY_URL}
      - IPFS_API_KEY=${IPFS_API_KEY}
      - IPFS_URL=${IPFS_URL}
      - MINTING_FEE=${MINTING_FEE}

  proxy:
    image: ethsign-api-nginx
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/:/etc/letsencrypt/
      - static_volume:/ethsigns-api/static/
    restart: always
volumes:
  static_volume:
  database_volume:
  redis_volume:
