"""add-element-and-force

Revision ID: 5ecc04306215
Revises: 707bd85de70e
Create Date: 2021-02-08 17:40:13.937215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ecc04306215'
down_revision = '707bd85de70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zodiacs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('element', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('force', sa.String(length=60), nullable=False))
        batch_op.create_index(batch_op.f('ix_zodiacs_element'), ['element'], unique=False)
        batch_op.create_index(batch_op.f('ix_zodiacs_force'), ['force'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zodiacs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zodiacs_force'))
        batch_op.drop_index(batch_op.f('ix_zodiacs_element'))
        batch_op.drop_column('force')
        batch_op.drop_column('element')

    # ### end Alembic commands ###
