"""add-element-and-force

Revision ID: 6adecd93a6db
Revises: 707bd85de70e
Create Date: 2021-02-07 21:13:09.779919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6adecd93a6db'
down_revision = '707bd85de70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zodiacs', sa.Column('element', sa.String(length=60), nullable=False))
    op.add_column('zodiacs', sa.Column('force', sa.String(length=60), nullable=False))
    op.create_index(op.f('ix_zodiacs_element'), 'zodiacs', ['element'], unique=False)
    op.create_index(op.f('ix_zodiacs_force'), 'zodiacs', ['force'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zodiacs_force'), table_name='zodiacs')
    op.drop_index(op.f('ix_zodiacs_element'), table_name='zodiacs')
    op.drop_column('zodiacs', 'force')
    op.drop_column('zodiacs', 'element')
    # ### end Alembic commands ###
