"""add-zodiac-model

Revision ID: 707bd85de70e
Revises: c7f85cbe4a7b
Create Date: 2021-02-06 21:21:43.279999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707bd85de70e'
down_revision = 'c7f85cbe4a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zodiacs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('image_url', sa.String(length=250), nullable=True),
    sa.Column('base_index', sa.Integer(), nullable=True),
    sa.Column('positive_traits', sa.String(length=500), nullable=True),
    sa.Column('negative_traits', sa.String(length=500), nullable=True),
    sa.Column('best_compatibility', sa.String(length=500), nullable=True),
    sa.Column('worst_compatibility', sa.String(length=500), nullable=True),
    sa.Column('report', sa.String(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zodiacs_base_index'), 'zodiacs', ['base_index'], unique=True)
    op.create_index(op.f('ix_zodiacs_best_compatibility'), 'zodiacs', ['best_compatibility'], unique=False)
    op.create_index(op.f('ix_zodiacs_name'), 'zodiacs', ['name'], unique=False)
    op.create_index(op.f('ix_zodiacs_negative_traits'), 'zodiacs', ['negative_traits'], unique=False)
    op.create_index(op.f('ix_zodiacs_positive_traits'), 'zodiacs', ['positive_traits'], unique=False)
    op.create_index(op.f('ix_zodiacs_report'), 'zodiacs', ['report'], unique=False)
    op.create_index(op.f('ix_zodiacs_worst_compatibility'), 'zodiacs', ['worst_compatibility'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zodiacs_worst_compatibility'), table_name='zodiacs')
    op.drop_index(op.f('ix_zodiacs_report'), table_name='zodiacs')
    op.drop_index(op.f('ix_zodiacs_positive_traits'), table_name='zodiacs')
    op.drop_index(op.f('ix_zodiacs_negative_traits'), table_name='zodiacs')
    op.drop_index(op.f('ix_zodiacs_name'), table_name='zodiacs')
    op.drop_index(op.f('ix_zodiacs_best_compatibility'), table_name='zodiacs')
    op.drop_index(op.f('ix_zodiacs_base_index'), table_name='zodiacs')
    op.drop_table('zodiacs')
    # ### end Alembic commands ###
