"""add-zodiac-model

Revision ID: 707bd85de70e
Revises: c7f85cbe4a7b
Create Date: 2021-02-06 21:21:43.279999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707bd85de70e'
down_revision = 'c7f85cbe4a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zodiacs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('image_url', sa.String(length=250), nullable=True),
    sa.Column('base_index', sa.Integer(), nullable=True),
    sa.Column('positive_traits', sa.String(length=500), nullable=True),
    sa.Column('negative_traits', sa.String(length=500), nullable=True),
    sa.Column('best_compatibility', sa.String(length=500), nullable=True),
    sa.Column('worst_compatibility', sa.String(length=500), nullable=True),
    sa.Column('report', sa.String(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zodiacs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zodiacs_base_index'), ['base_index'], unique=True)
        batch_op.create_index(batch_op.f('ix_zodiacs_best_compatibility'), ['best_compatibility'], unique=False)
        batch_op.create_index(batch_op.f('ix_zodiacs_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_zodiacs_negative_traits'), ['negative_traits'], unique=False)
        batch_op.create_index(batch_op.f('ix_zodiacs_positive_traits'), ['positive_traits'], unique=False)
        batch_op.create_index(batch_op.f('ix_zodiacs_report'), ['report'], unique=False)
        batch_op.create_index(batch_op.f('ix_zodiacs_worst_compatibility'), ['worst_compatibility'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zodiacs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zodiacs_worst_compatibility'))
        batch_op.drop_index(batch_op.f('ix_zodiacs_report'))
        batch_op.drop_index(batch_op.f('ix_zodiacs_positive_traits'))
        batch_op.drop_index(batch_op.f('ix_zodiacs_negative_traits'))
        batch_op.drop_index(batch_op.f('ix_zodiacs_name'))
        batch_op.drop_index(batch_op.f('ix_zodiacs_best_compatibility'))
        batch_op.drop_index(batch_op.f('ix_zodiacs_base_index'))
    # ### end Alembic commands ###
