"""add-day-sign-model

Revision ID: 8a83a646d265
Revises: fe729ae6026d
Create Date: 2021-02-17 10:25:07.954948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a83a646d265'
down_revision = 'fe729ae6026d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_sign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=60), nullable=False),
    sa.Column('animal', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('day_sign', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_day_sign_animal'), ['animal'], unique=False)
        batch_op.create_index(batch_op.f('ix_day_sign_day'), ['day'], unique=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day_sign', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_day_sign_day'))
        batch_op.drop_index(batch_op.f('ix_day_sign_animal'))

    op.drop_table('day_sign')
    # ### end Alembic commands ###
