"""nft model

Revision ID: b89d58804a88
Revises: e32e2d120eb6
Create Date: 2021-07-15 10:07:47.327653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b89d58804a88'
down_revision = 'e32e2d120eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NFT',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=700), nullable=False),
    sa.Column('metadata_url', sa.String(length=700), nullable=False),
    sa.Column('token_metadata', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('NFT', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_NFT_image_url'), ['image_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_NFT_metadata_url'), ['metadata_url'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NFT', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_NFT_metadata_url'))
        batch_op.drop_index(batch_op.f('ix_NFT_image_url'))

    op.drop_table('NFT')
    # ### end Alembic commands ###
