"""description-length

Revision ID: cc5dce03ad39
Revises: 5cfcf5cca19e
Create Date: 2021-05-11 13:55:47.075724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc5dce03ad39'
down_revision = '5cfcf5cca19e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zodiacs', schema=None) as batch_op:
        batch_op.alter_column('best_compatibility',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('negative_traits',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('positive_traits',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('worst_compatibility',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zodiacs', schema=None) as batch_op:
        batch_op.alter_column('worst_compatibility',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('positive_traits',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('negative_traits',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('best_compatibility',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
