"""user nfts

Revision ID: f570ad27301b
Revises: b89d58804a88
Create Date: 2021-07-22 09:44:10.401707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f570ad27301b'
down_revision = 'b89d58804a88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_nfts',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_nft', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['metamask_user.id'], ),
    sa.ForeignKeyConstraint(['user_nft'], ['NFT.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_nfts')
    # ### end Alembic commands ###
