"""add-month-zodiac-sign

Revision ID: fe729ae6026d
Revises: 5ecc04306215
Create Date: 2021-02-15 10:43:56.791060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe729ae6026d'
down_revision = '5ecc04306215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('month_sign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('animal', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('month_sign', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_month_sign_animal'), ['animal'], unique=False)
        batch_op.create_index(batch_op.f('ix_month_sign_month'), ['month'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('month_sign', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_month_sign_month'))
        batch_op.drop_index(batch_op.f('ix_month_sign_animal'))

    op.drop_table('month_sign')
    # ### end Alembic commands ###
