name: Ethsigns API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  run-tests:
    name: Run Tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Cache Dependencies
      uses: actions/cache@v2
      id: cache-venv
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m venv ~/.cache/pip/
        ~/.cache/pip/bin/activate
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        ~/.cache/pip/bin/activate
        # flake8 .
    - name: Test with pytest
      run: |
        ~/.cache/pip/bin/activate
        # coverage run -m pytest